### PR TITLE
Html support

### PR DESCRIPTION
**Pull request by yourpalal**
Because there are two websocket implementations ([dart:io](https://api.dartlang.org/stable/1.24.3/dart-io/WebSocket-class.html) and [dart:html](https://api.dartlang.org/stable/1.24.3/dart-html/WebSocket-class.html)), seperate code needs to be written to handle each.

In this pull request, I:

  * extracted a PhoenixConnection class from PhoenixSocket
  * made Html and IO versions of the PhoenixConnection interface
  * made Html and IO PhoenixSocket classes that inherit from the (now abstract) PhoenixSocket class and handle the creation of the html/io connections
  * cleaned up retries a little bit (await socket.connect() now waits for retries as well)
  * made most of the tests VM-only, but made the socket tests run on both VM and browser
  * made RemoteMockServer class for testing that wraps a MockServer. This is needed because when the tests are running in the browser, they need a server running outside of the browser, and they need to be able to communicate with it.
  * added a bit of documentation on the html/io stuff

Once this is merged in, I think the version should be updated, since this is a breaking change.

### CODE REVIEW

**Comment by mfeckie** [comment]
Thanks for submitting this PR.

I had deliberately not targeted browser compatibility as there was a library that existed which seemed to do that already ( https://github.com/sclee15/phoenix_channel ).

I wonder if adding browser compatibility is the right way to go with this library?  Happy to talk about that some more.

If we were to proceed, then I think there's a few things about the approach that you've presented that I'd prefer to be different.

I can see that you've done a great deal of work and that's awesome.  I especially like where you've gone with ensuring your PR is done with the addition of more tests.

The major area of contention for me would be around having the different classes to support the websocket connection type.  I feel like it would be better to have the top level `PhoenixSocket` class accept an optional `web socket provider` that would enable the user to target browser without having to choose a different class to instantiate.  The reason I feel this is important is that over time I think having two seperate classes allows the possibility of them diverging over time and not keeping API parity.

I think we could achieve what you are suggesting as a non-breaking change by following this approach.

More trivial, but also important to me are the changes to some of the code style. 

1. 'c' style single line returns without braces

Primary reasoning for this is that it's lead to hard to detect bugs in other codebases because it is much less obvious at first glance what's happening.  Low risk at this stage, but prefer to resolve it now.

```dart
if (_conn.readyState == WebSocket.OPEN) return this;
```

This would be acceptable

```dart
if (_conn.readyState == WebSocket.OPEN) { return this; }
```

This would be preferable

```dart
if (_conn.readyState == WebSocket.OPEN) { 
  return this; 
}
```

2. Variable / parameter naming

It's great that there are meaningful methods, but would appreciate naming things for the benefit of our future selves.

My questions when looking at this example are. What does `e` represent?  Why do we need to check it's a list?  Why to need to add to the sink?  What is the significance of element `[1]` of the result and why do we need to convert it to an `int`?  Given that this is a `getter`, should it be mutating something like the channel?  Generally getters should not have side effects, I think.

```dart
  Future<int> get heartbeat async {
    final result = _serverMessages.
      firstWhere((e) => (e is List && e[0] == "heartbeat"));
    _channel.sink.add("get_heartbeat");
    return (await result)[1] as int;
  }
```
3. complex if / else if / else

Consider https://github.com/yourpalal/phoenix_wings/blob/affd3da91fc63d45f9c42aa0a734a0f9f38cd72b/test/mock_server.dart#L143-L161

I think it'd be preferable to break it into two method calls. e.g.

```dart
if (message is String) {
  handleStringMessage(message, channel);
} else if (message is List) {
  handleListMessage(message, channel);
} else {
  throw new UnsupportedError("message not supported: $message");
}
```

and then use a switch or single clause if's to handle the individual cases.

```dart
switch (message) {
  case 'test_disconnect':
    await server.testDisconnect();
    channel.sink.add("test_disconnect returned");
    break; // or return channel.sink if appropriate
// etc
}
```

**Comment by yourpalal** [comment]
Hi, I wanted to use this library for web now, and hopefully sharing code with a flutter app later. By adding web support for this library, it makes this kind of code reuse as simple as possible. Not sure how often this actually comes up, but sharing code between Flutter & AngularDart apps (or other frameworks, I suppose) is one of the selling features of Dart, so it could be useful for others.

Injecting a web socket provider would be a nice design and I will look into that. The main aspect that drove me to the current design was that the PhoenixSocket class needs to be able to instantiate a connection multiple times. Rather than passing around static functions or closures or something, I figured this was easier.

I'm also not sure if it's possible to do this change without some breakage. I'm not sure if importing dart:io but not using it in the browser environment will cause problems. I'll try that and report back.

As for the style issues:

1. I'll fix these. I admit that I write them that way because it's faster, and to me it's cleaner. That said `dartfmt` prefers the style you do, so the whole tree can be made consistent in this very easily. I'll do a quick cleanup of the ones I added.

2. I'm extracting some private methods in RemoteMockServer for sending commands & receiving responses from the isolated MockServer. I'm also adding some comments explaining the protocol the RemoteMockServer uses to communicate to the MockServer.

As for the getter which sends & receives data, I think this is in line with the usage of RemoteMockServer as a proxy object. Although it's not as simple as retrieving a variable, the method is conceptually doing just that. This signature keeps it consistent with MockServer's interface which is also good. Finally, if we were to make it a named method, the most obvious name would be `getHeartbeat()` which to me would be more surprising than a getter that uses a channel.

3. Good point. I'll update mockserve'sr hybridMain() to use methods & switch.

thanks for the feedback! I'm basically done the style changes, the other part might take a bit longer as it requires some experimentation.

**Comment by yourpalal** [comment]
Fixed style issues & backwards-compatibility.

VM usage stays the same, but html usage can now be achieved with a slight change:

```dart
import 'package:phoenix_wings/html.dart';

var socket = new PhoenixSocket("ws://example.com", connectionProvider: PhoenixHtmlConnection.provider);
```

Interestingly, even importing `dart:html` on the VM causes it to crash, but importing and not using `dart:io` in the browser seems fine. Maybe due to tree-shaking? This works in the tests and I also tried it in an angular dart app.

**Comment by mfeckie** [comment]
Yeah, `dart:html` is totally incompatible with Flutter

**Comment by mfeckie** [comment]
Will take a deeper look at the update after work today

**Comment by yourpalal** [comment]
Hi @mfeckie, are you still interested in incorporating this change? If you have more changes to request I would be happy to do them. I think the ability to use the library in a web context could be very useful to others, so I would really like to get this change into pub if possible.

I saw that there's been another small PR accepted in the mean time. I can resolve that conflict this weekend, it should be pretty quick. I actually ended up doing something similar, because a test that called disconnect was failing intermittently due to the continuing reconnect attempts.

IIRC, there was another issue as well, that if the PhoenixSocket got a `closed` event after the user calling disconnect(), it would try to reconnect again, which I also fixed.

**Comment by mfeckie** [comment]
@yourpalal Yes, definitely still keen.

Apologies, I did checkout the PR and then there were a bunch of conflict with some recent updates to Flutter and I didn't have mental space to work through them.

If you fix up the conflicts I'll take a look at getting it merged ASAP

**Comment by yourpalal** [comment]
oh! just noticed you merged this!

Thanks :) I was working towards getting flutter up and running to do a test with the latest SDK, but I've been pretty busy lately so it was dragging on a bit!

**Pull request merged**
