### PR TITLE
make it possible to pass socket options as named args

### PR DESCRIPTION
**Pull request by lesnitsky**
Thanks for this package

as flutter dev I was confused with lack of possibility to pass options as named args. Consider adding this to the API 😏

### CODE REVIEW

**Review by mfeckie — APPROVED** [review]

**Comment by lesnitsky** [comment]
@mfeckie could you also publish a release with this change?

**Comment by mfeckie** [comment]
You might have to give me a few days as I'm changing laptop and haven't got my access keys for `pub` setup yet

**Comment by lesnitsky** [comment]
No problem, thanks

**Comment by mfeckie** [comment]
Actually, I published it just now.

**Comment by lesnitsky** [comment]
Kudos!

**Pull request merged**
